[project]
name = "crop-yield-prediction-api"
version = "0.1.0"
description = "Crop Yield Prediction using Linear Regression and FastAPI"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pandas",
    "numpy",
    "scikit-learn",
    "joblib",
    "python-multipart",
    "pydantic"
]